// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGdnxgzsKOUik7vmM_1CT0rIoHxrOS4Uo',
    appId: '1:559681981354:android:c51c6f03164d68060639d3',
    messagingSenderId: '559681981354',
    projectId: 'braceletlifesaver',
    databaseURL: 'https://braceletlifesaver-default-rtdb.firebaseio.com',
    storageBucket: 'braceletlifesaver.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAY5x-yv7dz-ZNm4lp0LJHsORr5H2KQUe8',
    appId: '1:559681981354:ios:cbd1a563d554570b0639d3',
    messagingSenderId: '559681981354',
    projectId: 'braceletlifesaver',
    databaseURL: 'https://braceletlifesaver-default-rtdb.firebaseio.com',
    storageBucket: 'braceletlifesaver.firebasestorage.app',
    iosBundleId: 'com.example.lifeStream',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQhwEA6Ral7EsLh4Z1ZQODJqciy1z4bX4',
    appId: '1:559681981354:web:17a1edb42f0a4c110639d3',
    messagingSenderId: '559681981354',
    projectId: 'braceletlifesaver',
    authDomain: 'braceletlifesaver.firebaseapp.com',
    databaseURL: 'https://braceletlifesaver-default-rtdb.firebaseio.com',
    storageBucket: 'braceletlifesaver.firebasestorage.app',
    measurementId: 'G-DSZL93QEXR',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAY5x-yv7dz-ZNm4lp0LJHsORr5H2KQUe8',
    appId: '1:559681981354:ios:cbd1a563d554570b0639d3',
    messagingSenderId: '559681981354',
    projectId: 'braceletlifesaver',
    databaseURL: 'https://braceletlifesaver-default-rtdb.firebaseio.com',
    storageBucket: 'braceletlifesaver.firebasestorage.app',
    iosBundleId: 'com.example.lifeStream',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQhwEA6Ral7EsLh4Z1ZQODJqciy1z4bX4',
    appId: '1:559681981354:web:17a1edb42f0a4c110639d3',
    messagingSenderId: '559681981354',
    projectId: 'braceletlifesaver',
    authDomain: 'braceletlifesaver.firebaseapp.com',
    databaseURL: 'https://braceletlifesaver-default-rtdb.firebaseio.com',
    storageBucket: 'braceletlifesaver.firebasestorage.app',
    measurementId: 'G-DSZL93QEXR',
  );

}