// File: lib/main.dart (FIXED)

import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:life_stream/app.dart';
import 'package:life_stream/providers/storage_provider.dart';
// NEW: Firebase Core import
import 'package:firebase_core/firebase_core.dart';
// FIX: Use the package path to correctly reference the generated file inside lib/
import 'package:life_stream/firebase_options.dart'; 

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // 1. Initialize Firebase Core
  // The DefaultFirebaseOptions is generated by the 'flutterfire configure' command
  try {
    await Firebase.initializeApp(
      options: DefaultFirebaseOptions.currentPlatform,
    );
  } catch (e) {
    debugPrint('Firebase initialization error: $e');
  }

  // Initialize storage before running the app (Existing code)
  final container = ProviderContainer();
  try {
    await container.read(initStorageProvider.future);
  } catch (e) {
    debugPrint('Storage initialization error: $e');
  }

  runApp(
    const ProviderScope(
      child: LifeStreamApp(),
    ),
  );
}